service: songbasket-backend
app: songbasket
org: joacoesteban

provider:
  name: aws
  runtime: nodejs12.x

stage: prod
region: us-east-1

environment:
  PRODUCTION: true

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'